### PR TITLE
Target ES5 for older browser compatbility

### PR DESCRIPTION
**Pull request by headlessme**
First of all, thanks for bringing this module back from the dead!

We're using cbor-js from our web frontend, and we still need to support IE11, so I'm hoping to add support for ES5 targets in the published version.

I don't think this PR quite fills all the requirements for IE11 yet – I think some polyfills are also needed for `Object.is` and `SharedArrayBuffer`. I'm not overly familiar with typescript so not sure whether these should be supplied by this module, as external, or if it's something typescript can do by itself.

### CODE REVIEW

**Comment by aaronhuggins** [comment]
Thank you for the compliment! I definitely see how an es5 version would be handy. Not sure that it should be the default tsconfig; I'll take a look this weekend and give it some thought. I *think* that the polyfills will be doable, but I'm not sure. Either way, I'd like to look at scaffolding another version to output at compile time.

Did you compile with this change and make sure it passes tests and gets you close to the result you're looking for? My only other concern is that I have no way I know of to add cross-platform IE11 tests. Any thoughts on that would be welcome.

**Comment by headlessme** [comment]
I managed to build with the es5 target and ran in IE11 successfully with the addition of those two polyfills (added externally). I only exercised the bits of the encoder/decoder we're using and didn't run the full test suite through IE yet, so there may be edge cases that need more attention.

I believe Karma can run tests against IE so long as it's running on a Windows platform: https://github.com/karma-runner/karma-ie-launcher

This might be a good option for running the tests in CI across a range of browsers?

**Comment by aaronhuggins** [comment]
What are you using to polyfill SharedArrayBuffer?

**Comment by headlessme** [comment]
I actually cheated and didn't use a proper polyfill. The code was only using `SharedArrayBuffer` as part of an `instanceof` check, so I just made sure the class was defined. Instead of polyfilling that class, the code could just check if it's available before trying to use it.

**Comment by ahuggins-nhs** [comment]
Yes, agreed, something like `typeof SharedArrayBuffer !== 'undefined' && value instanceof SharedArrayBuffer`.

It won't hurt to add the following polyfill, either. https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/is#Polyfill

**Comment by ahuggins-nhs** [comment]
I added some scaffolding for an es5 export. I'm not going to consider it official support especially since IE11 is trending to be less than 5% browser market share by the end of the year.

No guarantees that it will continue to work, or that I'll pay attention to supporting it long-term. It was fairly trivial to add, but if there's enough use of this library on modern browser/runtime contexts I may simply remove it to keep the download from NPM smaller. That doesn't mean users won't be able to browserify just like I did.

For now, unpkg is hosting: https://unpkg.com/cbor-redux@0.3.0/es5/CBOR.js

If this resolves your issue, feel free to close the pull request.

**Comment by aaronhuggins** [comment]
I added some scaffolding for an es5 export. I'm not going to consider it official support especially since IE11 is trending to be less than 5% browser market share by the end of the year.

No guarantees that it will continue to work, or that I'll pay attention to supporting it long-term. It was fairly trivial to add, but if there's enough use of this library on modern browser/runtime contexts I may simply remove it to keep the download from NPM smaller. That doesn't mean users won't be able to browserify just like I did.

For now, unpkg is hosting: https://unpkg.com/cbor-redux@0.3.0/es5/CBOR.js

If this resolves your issue, feel free to close the pull request.

**Pull request closed without merging**
