### PR TITLE
Release v1.0.0

### LINKED ISSUE #11: Forbid duplicate map keys during decoding
Maps with duplicate maps are not valid according to the CBOR spec. While the spec leaves it to the specific protocol where exactly this is dealt with I think it would be trivial to add this check to cbor-redux in this code path: 
https://github.com/aaronhuggins/cbor-redux/blob/22ba58fb7d8d30e2fc85c2f9dbad6f7c53785037/src/CBOR.ts#L230-L236

### LINKED ISSUE #15: Support ESM in Node, or move to ESM-only
First, thanks so much for writing this library! It's been awesome to watch the Deno ecosystem grow, and great to have a minimal modern CBOR implementation.

I'm writing an ESM-only library for use in Node, the browser, and Deno. However, the way cbor-redux is structured doesn't actually let me use it in Node by default:

```js
// test.mjs
import { CBOR } from "cbor-redux"
console.log(CBOR)
```

```
% node test.mjs
file:///Users/.../test.mjs:1
import { CBOR } from "cbor-redux";
         ^^^^
SyntaxError: Named export 'CBOR' not found. The requested module 'cbor-redux' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from 'cbor-redux';
const { CBOR } = pkg;

    at ModuleJob._instantiate (internal/modules/esm/module_job.js:121:21)
    at async ModuleJob.run (internal/modules/esm/module_job.js:166:5)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

This is because Node.js supports native ESM modules, but _only_ interprets an imported library as an ESM module if it has `"type": "module"` in package.json.

This is independent of the `exports` map in package.json. Node.js _is_ trying to load `./esm/CBOR.js`, but when it does will try to parse it as a CommonJS module (which will fail). For example:

```js
// test2.mjs
import CBOR from "cbor-redux"
console.log(CBOR)
```

```
% node test2.mjs
(node:23296) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.
(Use `node --trace-warnings ...` to show where the warning was created)
/Users/.../node_modules/cbor-redux/esm/CBOR.js:22
export class TaggedValue {
^^^^^^

SyntaxError: Unexpected token 'export'
    at wrapSafe (internal/modules/cjs/loader.js:988:16)
    at Module._compile (internal/modules/cjs/loader.js:1036:27)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at ModuleWrap.<anonymous> (internal/modules/esm/translators.js:199:29)
    at ModuleJob.run (internal/modules/esm/module_job.js:170:25)
    at async Loader.import (internal/modules/esm/loader.js:178:24)
    at async Object.loadESM (internal/process/esm_loader.js:68:5)
```

---

There are a variety of ways to support this, but the simplest is just moving ESM-only and leaving CommonJS behind entirely. There's an massive ongoing movement across the OSS web ecosystem to do this, summarized by Sindre Sorhus here: https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c

The upside is that you could have a single unified ESM `dist` target that works for Node and the browser (Deno is obviously a separate thing); the downside is that it involves tinkering with however the library is built, which is always annoying, and releasing a new major version that no longer support old versions of Node (< v12).

Is this something you'd consider? I know it's exhausting to continually change export formats but I think it's become clear that ESM-only is truly the one long-term stable universal solution for JS.

### LINKED ISSUE #16: Add support for encoding numeric keys in maps
The library only accepts plain JS objects to represent CBOR maps, which prevents using numbers as keys. It would be good if JS `Map` could be supported as that allows any type as key, in which case numbers could be used.

### LINKED ISSUE #17: Migrate library for improved Deno support
In preparation for some Deno prod work in a private project, I'm prepping for a v1.0 release. The goal is to heavily simplify the codebase, improve the deployment process, and reduce load to maintain the library.

- [x] Release v0.4.0 on npm #10
- [x] Merge all outstanding PRs #13
- [x] Use inclusive branch naming, i.e. `main`
- [x] Remove all node-specific configuration
- [x] Clean up codebase for vanilla Deno support #15
- [x] Add Deno test suite
- [x] Add support for encoding numeric keys in maps #16
- [x] Add Deno config
- [x] Add support for [Deno to Node Tool](https://github.com/denoland/dnt)
- [x] Forbid duplicate map keys during decoding #11
- [x] Add Github CI/CD pipeline
- [x] Deploy v1 to Deno.Land/x and NPM #17

### PR DESCRIPTION
**Pull request by aaronhuggins**
Major version change, with definitely breaking changes!

- Redesigned API to align with the `JSON` API in ECMAScript
  - Dropped support in the decoder for `taggedValue` and `simpleValue` callbacks
  - `encode` now takes an optional `replacer` function argument to align with `JSON.stringify`
  - `decode` now takes an optional `reviver` function argument to align with `JSON.parse`
  - `decode` not takes an optional object to set `mode` and `dictionary` behaviors
  - Aliases of `parse` for `decode` and `binarify` for `encode` are now exported
  - Added `Sequence` class for encoding and decoding CBOR Sequences
  - Improved `TaggedValue` to accept `number` or `bigint` tags
  - Improved `SimpleValue` for use as a round-trip encode/decode mechanism
- Updates to decode and encode algorithms to conform very closely to RFC 8949, the latest CBOR revision
- Adds lots of other RFCs
  - Typed Arrays (RFC 8746)
  - CBOR Sequences (RFC 8742)
  - Strictness (required for COSE RFC 8152)
- Support for `bigint`; applications *will* now get `bigint` for integers outside the ECMAScript `number` safe range
- Support for `Map`; applications may use Map to encode and decode non-string keys
- Refactored code to target Deno
- Code is transpiled for Node.js using both ES Modules and CommonJS

### CODE REVIEW

**Comment by kdubb** [comment]
@aaronhuggins Any thoughts when a this will happen?

**Comment by kdubb** [comment]
And BTW thanks for all this hard work. It's nice to be able to just update when in need of deterministic encoding instead of switching packages!

**Comment by aaronhuggins** [comment]
Hey @kdubb! Thanks for the kind words. I went through a period of illness and haven't had an opportunity until this AM to revisit this. I'm going to take a look here and see what I can do to get this across the line.

**Comment by kdubb** [comment]
Very sorry to hear. If you need any help I can pitch in. I maintain a Swift CBOR parser and am quite experienced in TypeScript. Thanks for the work and wishing you all the best for your health!

**Comment by aaronhuggins** [comment]
@kdubb I gotchu

NPM (ESM and CJS): https://www.npmjs.com/package/cbor-redux

Deno: https://deno.land/x/cbor_redux@1.0.0

Browser ESM: https://deno.land/x/cbor_redux@1.0.0/web/mod.js

Browser script: https://deno.land/x/cbor_redux@1.0.0/web/polyfill.js

**Comment by kdubb** [comment]
🎉 You Rock! Thank You!

**Comment by aaronhuggins** [comment]
@kdubb One last thing... I'd love to avoid bitrot. If you're willing, I've sent you an invite to collab on the repo.

**Comment by kdubb** [comment]
@aaronhuggins I'm up for that!

**Pull request merged**
